version: '3'

services:
  sodaadminwebfront:
    image: soda-admin-node-pnpm:latest
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 6000:3000
      - 6001:3001
    environment:
      - API_URL=https://admin-api.dev.lawtalksoda.com
    expose:
      - 6000
      - 6001
    networks:
      priros_local_network:
    command: ['sh', '-c', 'pnpm dev']
networks:
  priros_local_network:
    external: true
